spring.application.name=tochka-messenger
jwt.access.secret=ваш_base64_код_access_ключа_минимум_32_байта
jwt.refresh.secret=ваш_base64_код_refresh_ключа_минимум_32_байта
# application.properties
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=lax
# Для продакшена обязательно:
# server.ssl.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/tochka_messenger
spring.datasource.username=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=9090