spring.application.name=tochka-messenger
spring.datasource.url=jdbc:postgresql://localhost:5432/ИМЯ_ТВОЕЙ_БД
spring.datasource.username=postgres
spring.datasource.password=ТВОЙ_ПАРОЛЬ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.access.secret=ваш_base64_код_access_ключа_минимум_32_байта
jwt.refresh.secret=ваш_base64_код_refresh_ключа_минимум_32_байта
